---
- name: Configure Cisco switches
  hosts: all
  gather_facts: false
  tasks:
    - name: Configure SCP on switches
      include_tasks: playbooks/roles/cisco_switch/tasks/configure_scp.yml

    - name: Apply configuration from template
      ios_config:
        src: playbooks/roles/cisco_switch/templates/config.j2

    - name: Save running-config to startup-config
      ios_config:
        save_when: always